- set number
-- set numbers to linem
- set autoindent
-- get new line with proper indentation
- set tabstop=4
-- set Tab spaces
- set shiftwidth=4 -- set sapace after new line
- syntax on
-- Highlight syntax
- set nowrap
-- Continue line type
- set autowriteall -- Like Auto Save
- set cursorline
-- Highlight cursor line
